---
title: "Tropical Cyclone Analysis"
author: "Caroline Williams"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
vignette: >
  %\VignetteIndexEntry{Cyclone Analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load libraries
library(dplyr)
library(sf)
library(tidyr)
library(raster)
```

### Read in data
#### read in CSVs
```{r, eval = FALSE}
# read in csv files
# read in NA Basin
NA_basins <- read.csv(system.file("extdata/ibtracs.NA.list.v04r00.csv", package = "cyclone"))

# read in EP Basin
EP_basins <- read.csv(system.file("extdata/ibtracs.EP.list.v04r00.csv", package = "cyclone"))

# read in NI Basin
NI_basins <- read.csv(system.file("extdata/ibtracs.NI.list.v04r00.csv", package = "cyclone"))

# read in SA Basin
SA_basins <- read.csv(system.file("extdata/ibtracs.SA.list.v04r00.csv", package = "cyclone"))

# read in SI Basin
SI_basins <- read.csv(system.file("extdata/ibtracs.SI.list.v04r00.csv", package = "cyclone"))

# read in SP Basin
SP_basins <- read.csv(system.file("extdata/ibtracs.SP.list.v04r00.csv", package = "cyclone"))

# read in WP Basin
WP_basins <- read.csv(system.file("extdata/ibtracs.WP.list.v04r00.csv", package = "cyclone"))
```

#### read in shapefiles
```{r}
# read in NA Basin
NA_basins <- st_read(system.file("extdata/IBTrACS.NA.list.v04r00.lines.shp", package = "cyclone"))

# read in EP Basin
EP_basins <- st_read(system.file("extdata/IBTrACS.EP.list.v04r00.lines.shp", package = "cyclone"))

# read in NI Basin
NI_basins <- st_read(system.file("extdata/IBTrACS.NI.list.v04r00.lines.shp", package = "cyclone"))

# read in SA Basin
SA_basins <- st_read(system.file("extdata/IBTrACS.SA.list.v04r00.lines.shp", package = "cyclone"))

# read in SI Basin
SI_basins <- st_read(system.file("extdata/IBTrACS.SI.list.v04r00.lines.shp", package = "cyclone"))

# read in SP Basin
SP_basins <- st_read(system.file("extdata/IBTrACS.SP.list.v04r00.lines.shp", package = "cyclone"))

# read in WP Basin
WP_basins <- st_read(system.file("extdata/IBTrACS.WP.list.v04r00.lines.shp", package = "cyclone"))
```


### Data Analysis
#### NA Basin
```{r, eval = FALSE}
# sorting/ tidying
NA_sort <- NA_basins %>% dplyr::select(SID, SEASON, NUMBER, BASIN, NAME, ISO_TIME, LAT, LON, WMO_WIND, DIST2LAND, LANDFALL) %>% separate(., "ISO_TIME", c("YEAR", "MONTH", "DATE"), sep= "-") %>% separate(., "DATE", c("DATE", "TIME"), sep= " ")

# Intensity 
NA_wind <- NA_sort %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

NA_intensity <- NA_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
NA_hist <- NA_sort %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

NA_frequency <- NA_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```

#### EP Basin
```{r, eval = FALSE}
# sorting/ tidying
EP_sort <- EP_basins %>% dplyr::select(SID, SEASON, NUMBER, BASIN, NAME, ISO_TIME, LAT, LON, WMO_WIND, DIST2LAND, LANDFALL) %>% separate(., "ISO_TIME", c("YEAR", "MONTH", "DATE"), sep= "-") %>% separate(., "DATE", c("DATE", "TIME"), sep= " ")

# Intensity 
EP_wind <- EP_sort %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

EP_intensity <- EP_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
EP_hist <- EP_sort %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

EP_frequency <- EP_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```

#### NI Basin
```{r, eval = FALSE}
# sorting/ tidying
NI_sort <- NI_basins %>% dplyr::select(SID, SEASON, NUMBER, BASIN, NAME, ISO_TIME, LAT, LON, WMO_WIND, DIST2LAND, LANDFALL) %>% separate(., "ISO_TIME", c("YEAR", "MONTH", "DATE"), sep= "-") %>% separate(., "DATE", c("DATE", "TIME"), sep= " ")

# Intensity 
NI_wind <- NI_sort %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

NI_intensity <- NI_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
NI_hist <- NI_sort %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

NI_frequency <- NI_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```

#### SA Basin
```{r, eval = FALSE}
# sorting/ tidying
SA_sort <- SA_basins %>% dplyr::select(SID, SEASON, NUMBER, BASIN, NAME, ISO_TIME, LAT, LON, WMO_WIND, DIST2LAND, LANDFALL) %>% separate(., "ISO_TIME", c("YEAR", "MONTH", "DATE"), sep= "-") %>% separate(., "DATE", c("DATE", "TIME"), sep= " ")

# Intensity 
SA_wind <- SA_sort %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

SA_intensity <- SA_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
SA_hist <- SA_sort %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

SA_frequency <- SA_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```

#### SI Basin
```{r, eval = FALSE}
# sorting/ tidying
SI_sort <- SI_basins %>% dplyr::select(SID, SEASON, NUMBER, BASIN, NAME, ISO_TIME, LAT, LON, WMO_WIND, DIST2LAND, LANDFALL) %>% separate(., "ISO_TIME", c("YEAR", "MONTH", "DATE"), sep= "-") %>% separate(., "DATE", c("DATE", "TIME"), sep= " ")

# Intensity 
SI_wind <- SI_sort %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

SI_intensity <- SI_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
SI_hist <- SI_sort %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

SI_frequency <- SI_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```

#### SP Basin
```{r, eval =  FALSE}
# sorting/ tidying
SP_sort <- SP_basins %>% dplyr::select(SID, SEASON, NUMBER, BASIN, NAME, ISO_TIME, LAT, LON, WMO_WIND, DIST2LAND, LANDFALL) %>% separate(., "ISO_TIME", c("YEAR", "MONTH", "DATE"), sep= "-") %>% separate(., "DATE", c("DATE", "TIME"), sep= " ")

# Intensity 
SP_wind <- SP_sort %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

SP_intensity <- SP_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
SP_hist <- SP_sort %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

SP_frequency <- SP_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```

#### WP Basin
```{r, eval = FALSE}
# sorting/ tidying
WP_sort <- WP_basins %>% dplyr::select(SID, SEASON, NUMBER, BASIN, NAME, ISO_TIME, LAT, LON, WMO_WIND, DIST2LAND, LANDFALL) %>% separate(., "ISO_TIME", c("YEAR", "MONTH", "DATE"), sep= "-") %>% separate(., "DATE", c("DATE", "TIME"), sep= " ")

# Intensity 
WP_wind <- WP_sort %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

WP_intensity <- WP_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
WP_hist <- WP_sort %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

WP_frequency <- WP_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```

### Country-Scale: Vietnam
```{r}
# create bounding box
pol <- st_polygon(list(cbind(x = c(105, 120, 120, 105, 105), 
                             y = c(5, 5, 20, 20, 5))))

# convert basin to sf object
WP_sf <- WP_sort %>% .[-1,] %>% mutate(LON = LON %>% as.numeric(!is.na("LON"))) %>% mutate(LAT = LAT %>% as.numeric(!is.na("LAT"))) %>% st_as_sf(coords = c("LON", "LAT"), crs = 4326)

# project Vietnam bounding box
pol_sf <- pol %>% st_sfc %>% st_sf(ID = 1, crs = 4326) %>% st_transform(st_crs(WP_sf))

Vietnam_sf <- WP_sf %>% slice(st_intersects(x = pol_sf, y = WP_sf)[[1]])
#p <- plot(Vietnam_sf)

# Intensity 
Viet_wind <- Vietnam_sf %>% filter(WMO_WIND > 0) %>% group_by(SID, YEAR) %>% summarize(INTENSITY = mean(WMO_WIND %>% as.numeric()))

Viet_intensity <- Viet_wind %>% group_by(YEAR) %>% summarize(INTENSE_YRS = mean(INTENSITY)) %>% mutate(YEAR = YEAR %>% as.numeric())

# Frequency
Viet_hist <- Vietnam_sf %>% group_by(SID, YEAR) %>% summarize(FREQ = frequency(SID %>% as.numeric()))

Viet_frequency <- Viet_hist %>% group_by(YEAR) %>% summarize(FREQ_YRS = sum(FREQ)) %>% mutate(YEAR = YEAR %>% as.numeric())
```


# spatial grid test
```{r}
# SIDs with WMO_WIND > 0
Viet_WMO <- Vietnam_sf %>% filter(WMO_WIND > 0)
# write object for each Storm Track
for(i in unique(Viet_WMO$SID)) {
  list_data <- split(Viet_WMO, Viet_WMO$SID)
  names(list_data) <- paste0("vietnam_", names(list_data))
  list2env(list_data, .GlobalEnv)
  st_write(Viet_WMO, paste0(i), append = TRUE)
}

# create blank raster
r_temp <- raster(x = extent(pol_sf), crs = crs(pol_sf), res = 0.1)

r_temp2 <- raster(x = extent(pol_sf), crs = crs(pol_sf), res = 0.001)
#SID_raster <- rasterize(vietnam_2019308N13114, r_temp, "WMO_WIND")

# create list of "vietnam_"
WMO_list <- mget(ls(pattern="vietnam_"))

# Convert each SID object to raster based on WMO_WIND ~1980 to present
r_list <- lapply(WMO_list, function(x) {
  rasterize(x, r_temp, "WMO_WIND")
  }
)

# testing
r_buff_test <- st_buffer(WMO_list$vietnam_1977161N06134, 10)
raster::extract()

mult <- r_buff_test - r_list$vietnam_1977161N06134

r_buff_test_vct <- raster::rasterToPolygons(r_buff_test)

r_extract <- raster::extract(r_list$vietnam_1977161N06134, r_buff_test_vct, method = "bilinear")

r_buff <- lapply(r_list, function(x) {
  raster::buffer(x, width = 300000)
  }
)

r_stack <- raster::stack(r_list)

# calculate mean of raster strom tracks
mean <- calc(r_stack, fun = mean, na.rm = T)

# testing continued
density <- density(mean, plot = TRUE)


r_zonal <- zonal(r_list$vietnam_1977161N06134, r_buff_test, fun='mean', digits=0, na.rm=TRUE) 
# smoothing
smooth_d <- raster::aggregate(mean, 5, method='bilinear')
r_resamp <- resample(mean, r_temp2, method = "bilinear")

# convert into risk 1-5
m <- c(0, 20, 1,  
       20, 40, 2,  
       40, 60, 3,
       60, 80, 4,
       80, 99999, 5)
rec <- matrix(m, ncol=3, byrow=TRUE)
r_reclass <- reclassify(mean, rcl = rec)

ds <- spatstat::densityHeat(mean) 
r <- raster(ds)
plot(r)

#writeRaster(mean, "C:/Users/Caroline/Documents/Projects/cyclone/inst/extdata/tc_lines_raster.tif")
```
