---
title: "Data Download - IBTrACS"
author: "Caroline Williams"
output:
  prettydoc::html_pretty:
    theme: leonids
    highlight: github
vignette: >
  %\VignetteIndexEntry{Download Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tropical Cyclone Analysis in N. America

### Download IBTrACS storm data
Data url: https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/

```{r}
# load libraries
library(rnoaa)
library(curl)
library(utils)
library(sp)
library(dplyr)
library(sf)
library(ggplot2)
library(tidyr)
library(FedData)
```

# Download CSVs
```{r, eval = FALSE}
# download basins data from NOAA Ibtracs
# NA Basin
download.file("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.NA.list.v04r00.csv", "inst/extdata/ibtracs.NA.list.v04r00.csv")

# EP Basin
download.file("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.EP.list.v04r00.csv", "inst/extdata/ibtracs.EP.list.v04r00.csv")

# NI Basin
download.file("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.NI.list.v04r00.csv", "inst/exdata/ibtracs.NI.list.v04r00.csv")

# SA Basin
download.file("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.SA.list.v04r00.csv", "inst/extdata/ibtracs.SA.list.v04r00.csv")

# SI Basin
download.file("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.SI.list.v04r00.csv", "inst/extdata/ibtracs.SI.list.v04r00.csv")

# SP Basin
download.file("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.SP.list.v04r00.csv", "inst/extdata/ibtracs.SP.list.v04r00.csv")

# WP Basin
download.file("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.WP.list.v04r00.csv", "inst/extdata/ibtracs.WP.list.v04r00.csv")
```

# Download Line Shapefiles
```{r}
urls <- list("https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NA.list.v04r00.lines.zip", 
             "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.EP.list.v04r00.lines.zip",
             "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.NI.list.v04r00.lines.zip",
             "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.SA.list.v04r00.lines.zip",
             "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.SI.list.v04r00.lines.zip",
             "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.SP.list.v04r00.lines.zip",
             "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/shapefile/IBTrACS.WP.list.v04r00.lines.zip")

tc_dir <- "C:/Users/Caroline/Documents/Projects/cyclone/inst/extdata" # specify the file path for the output 
# system.file("extdata", package = "cyclone")
# iterate through .zip files 
for (i in urls) {
  tmp <- tempfile(tmpdir = tc_dir, fileext = ".zip")
  download.file(i, tmp)
  unzip(tmp,exdir = tc_dir)
  unlink(tmp)
  fp <- list.files(path = tc_dir, full.names = TRUE, pattern = "ibtracs")
  fp <- gsub("/", "\\\\", fp)
}
```

